import { webcrypto as crypto } from 'node:crypto';
const ORIGIN = 'https://qingnian-laowu.netlify.app';
const REPO = 'wuhaozhuo6666-ctrl/qingnian-laowu';
const OWNER_ID = 327517365;
const FILE = '/repos/' + REPO + '/contents/products/catalog.json';
const LIMITS = {name:80,wood:100,size:160,desc:1600,options:400,price:200};
const enc = new TextEncoder();
const dec = new TextDecoder();
const b64 = bytes => btoa(String.fromCharCode(...bytes));
const un64 = str => Uint8Array.from(atob(str), c => c.charCodeAt(0));
const url64 = bytes => b64(bytes).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const random = () => url64(crypto.getRandomValues(new Uint8Array(32)));
function cookie(req,name){return (req.headers.get('Cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='))?.slice(name.length+1)||'';}
function setCookie(name,value,age){return name+'='+value+'; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age='+age;}
async function key(env){const bytes=await crypto.subtle.digest('SHA-256',enc.encode('laowu-admin-session-v1:'+env.GITHUB_CLIENT_SECRET));return crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['encrypt','decrypt']);}
async function seal(value,env){const iv=crypto.getRandomValues(new Uint8Array(12));const body=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(env),enc.encode(JSON.stringify(value)));return b64(iv)+'.'+b64(new Uint8Array(body));}
async function unseal(value,env){try{const [iv,body]=value.split('.');const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:un64(iv)},await key(env),un64(body));const data=JSON.parse(dec.decode(raw));return data.exp>Date.now()?data:null;}catch{return null;}}
function reply(body,status=200,extra={}){return new Response(typeof body==='string'?body:JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY',...extra}});}
function redirect(path,cookies=[]){const headers=new Headers({'Location':path,'Cache-Control':'no-store','Referrer-Policy':'no-referrer'});for(const c of cookies)headers.append('Set-Cookie',c);return new Response(null,{status:303,headers});}
async function github(path,token,options={}){const response=await fetch('https://api.github.com'+path,{...options,headers:{'Authorization':'Bearer '+token,'Accept':'application/vnd.github+json','User-Agent':'laowu-product-admin','X-GitHub-Api-Version':'2022-11-28',...(options.body?{'Content-Type':'application/json'}:{})}});if(!response.ok){const e=new Error('GitHub request failed');e.status=response.status;throw e;}return response.status===204?null:response.json();}
async function readCatalog(token){const file=await github(FILE+'?ref=main',token);const data=JSON.parse(dec.decode(un64(file.content.replace(/\s/g,''))));if(!Array.isArray(data.products))throw Error('Invalid catalog');return {sha:file.sha,products:data.products};}
function applyChanges(products,changes){if(!Array.isArray(changes)||changes.length>500)throw Error('Invalid changes');const next=products.map(p=>({...p}));const seen=new Set();for(const change of changes){if(!change||typeof change.id!=='string'||seen.has(change.id))throw Error('Invalid product');seen.add(change.id);const p=next.find(p=>p.id===change.id);if(!p||!change.fields||typeof change.fields!=='object'||Array.isArray(change.fields))throw Error('Invalid product');for(const [field,value] of Object.entries(change.fields)){if(!Object.hasOwn(LIMITS,field)||typeof value!=='string'||value.length>LIMITS[field]||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value))throw Error('Invalid field');if(field==='name'&&!value.trim())throw Error('Name required');p[field]=value.trim();}}return next;}
const worker = {async fetch(request,env){
 try{
  const url=new URL(request.url);
  if(url.origin!==ORIGIN)return reply({error:'地址不匹配。'},400);
  if(!env.GITHUB_CLIENT_ID||!env.GITHUB_CLIENT_SECRET)return reply({error:'请先配置 GITHUB_CLIENT_ID 和 GITHUB_CLIENT_SECRET。'},503);
  if(request.method==='POST'&&(request.headers.get('Origin')!==ORIGIN||!request.headers.get('Content-Type')?.startsWith('application/json')))return reply({error:'请求来源不正确。'},403);
  if(url.pathname==='/admin/login'&&request.method==='GET'){
   const state=random(),verifier=random();const challenge=url64(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(verifier))));const auth=new URL('https://github.com/login/oauth/authorize');auth.search=new URLSearchParams({client_id:env.GITHUB_CLIENT_ID,redirect_uri:ORIGIN+'/admin/callback',scope:'public_repo',state,code_challenge:challenge,code_challenge_method:'S256',login:'wuhaozhuo6666-ctrl',allow_signup:'false'}).toString();return redirect(auth.href,[setCookie('__Host-laowu-flow',await seal({state,verifier,exp:Date.now()+600000},env),600)]);
  }
  if(url.pathname==='/admin/callback'&&request.method==='GET'){
   const flow=await unseal(cookie(request,'__Host-laowu-flow'),env);if(!flow||!url.searchParams.get('state')||flow.state!==url.searchParams.get('state')||!url.searchParams.get('code'))return reply({error:'登录验证失效，请重新打开 /admin/login 登录。'},400);
   const r=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{'Accept':'application/json','Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.GITHUB_CLIENT_ID,client_secret:env.GITHUB_CLIENT_SECRET,code:url.searchParams.get('code'),redirect_uri:ORIGIN+'/admin/callback',code_verifier:flow.verifier})});const token=await r.json();if(!r.ok||!token.access_token)return reply({error:'GitHub 登录未完成，请重新登录。'},401);
   const user=await github('/user',token.access_token);if(user.id!==OWNER_ID)return reply({error:'此账号没有本店管理权限，请使用店主 GitHub 账号登录。'},403);
   const age=Math.max(1,Math.min(3600,Number(token.expires_in)||3600));const session={token:token.access_token,uid:user.id,csrf:random(),exp:Date.now()+age*1000};return redirect('/admin/',[setCookie('__Host-laowu-session',await seal(session,env),age),setCookie('__Host-laowu-flow','',0)]);
  }
  if((url.pathname==='/admin/'||url.pathname==='/admin')&&request.method==='GET'){const nonce=random();return reply(ADMIN.replaceAll('NONCE_VALUE',nonce),200,{'Content-Type':'text/html; charset=utf-8','Content-Security-Policy':"default-src 'none'; script-src 'nonce-"+nonce+"'; style-src 'nonce-"+nonce+"'; img-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"});}
  if(!url.pathname.startsWith('/admin/api/'))return reply({error:'页面不存在。'},404);
  const session=await unseal(cookie(request,'__Host-laowu-session'),env);if(!session||session.uid!==OWNER_ID)return reply({error:'请登录。'},401);
  if(request.method==='POST'&&request.headers.get('X-CSRF-Token')!==session.csrf)return reply({error:'验证过期，请重新登录。'},403);
  if(url.pathname==='/admin/api/logout'&&request.method==='POST')return reply({ok:true},200,{'Set-Cookie':setCookie('__Host-laowu-session','',0)});
  // Recheck identity for each data request; GitHub enforces repository write permission.
  const user=await github('/user',session.token);if(user.id!==OWNER_ID)return reply({error:'没有管理权限。'},403);
  if(url.pathname==='/admin/api/catalog'&&request.method==='GET')return reply({...await readCatalog(session.token),csrf:session.csrf});
  if(url.pathname==='/admin/api/catalog'&&request.method==='POST'){
   if(Number(request.headers.get('Content-Length')||0)>100000)return reply({error:'提交内容过大。'},413);
   const raw=await request.text();if(enc.encode(raw).length>100000)return reply({error:'提交内容过大。'},413);
   let data;try{data=JSON.parse(raw);}catch{return reply({error:'数据格式错误。'},400);}
   const current=await readCatalog(session.token);if(data.sha!==current.sha)return reply({error:'资料已在其他页面更新。请先复制保留你的修改，再重新加载，避免覆盖。'},409);
   let products;try{products=applyChanges(current.products,data.changes);}catch{return reply({error:'字段无效、超长或产品名称为空。'},400);}
   if(!data.changes.length)return reply({error:'没有需要发布的修改。'},400);
   const bytes=enc.encode(JSON.stringify({products},null,2)+'\n');let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);
   const result=await github(FILE,session.token,{method:'PUT',body:JSON.stringify({branch:'main',sha:current.sha,message:'Update product details from store admin',content:btoa(binary)})});return reply({sha:result.content.sha,products,message:'资料已保存，顾客网站正在自动更新，请稍后查看。'});
  }
  return reply({error:'不支持的操作。'},405);
 }catch(error){return reply({error:error.status===401?'登录已过期，请重新登录；未发布的修改仍保留在页面中。':error.status===409||error.status===422?'发生版本冲突，未覆盖现有资料。请保留修改后重新加载。':'服务暂时不可用，请稍后重试。'},error.status===401?401:error.status===409||error.status===422?409:502);}
}};
const ADMIN = String.raw`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>青年老吴 · 产品管理</title><style nonce="NONCE_VALUE">
*{box-sizing:border-box}body{margin:0;background:#f4f2eb;color:#26382f;font:16px/1.6 system-ui,sans-serif}main{max-width:1050px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;gap:16px;border-bottom:1px solid #ccd3c8;padding-bottom:16px}h1{font-size:25px;margin:0}h2{font-size:21px}p{color:#5c695d}a{color:#304e3c}button,.login{border:1px solid #b5bfae;border-radius:8px;padding:10px 16px;background:#fff;color:#26382f;font:inherit;cursor:pointer}.primary,.login{background:#304e3c;color:white;text-decoration:none}button:disabled{opacity:.5;cursor:default}.toolbar{display:flex;flex-wrap:wrap;gap:10px;margin:20px 0}input,textarea{font:inherit;padding:10px;border:1px solid #aab5a7;border-radius:6px;width:100%;background:#fff;color:#26382f}textarea{min-height:110px;resize:vertical}label{display:block;font-size:14px}label span{display:block;margin-bottom:5px}.products{display:grid;gap:20px}.product{padding:20px;border:1px solid #d7ddd0;border-radius:12px;background:#fffef9;display:grid;grid-template-columns:180px 1fr;gap:24px}.product img{width:100%;height:240px;object-fit:contain;background:#eceae2}.fields{display:grid;grid-template-columns:1fr 1fr;gap:14px}.wide{grid-column:1/-1}.product small{display:block;color:#657160;margin-top:8px}.status{padding:12px 0;white-space:pre-wrap}.preview{border:1px solid #b8c4b3;background:white;padding:20px;margin-top:20px;border-radius:10px}.change{padding:12px 0;border-bottom:1px solid #ddd}.change p{white-space:pre-wrap;overflow-wrap:anywhere}.loginbox{padding:36px 0}.hint{font-size:14px}.dirty{color:#8d542d}[hidden]{display:none!important}:focus-visible{outline:3px solid #9a6846;outline-offset:3px}@media(max-width:600px){main{padding:16px}.product{grid-template-columns:1fr}.product img{height:180px}.fields{grid-template-columns:1fr}header{align-items:start;flex-direction:column}.toolbar{position:sticky;top:0;background:#f4f2eb;padding:10px 0;z-index:2}}
</style></head><body><main><header><div><h1>青年老吴 · 产品管理</h1><div class="hint">修改资料 → 预览修改 → 发布</div></div><a href="https://qingnian-laowu.netlify.app/" target="_blank" rel="noopener">查看顾客网站 ↗</a></header><div id="status" class="status" role="status"></div><section id="loginBox" class="loginbox" hidden><p>请使用店主 GitHub 账号登录。登录有效期最长一小时。</p><a class="login" href="/admin/login" target="_blank" rel="noopener">使用 GitHub 登录</a><button id="resume">登录后继续当前编辑</button></section><section id="editor" hidden><div class="toolbar"><button id="preview" class="primary">预览修改</button><button id="backup">复制未发布修改</button><button id="reload">重新加载</button><button id="logout">退出登录</button></div><p class="hint">这里填写的内容会展示给顾客。第一版支持名称、木材、尺寸、说明、定制项目和报价说明；照片与编号保持原样。</p><input id="search" type="search" placeholder="搜索产品名称或编号" aria-label="搜索产品"><p id="count"></p><section id="previewPanel" class="preview" hidden><h2>确认要发布的修改</h2><div id="changes"></div><button id="publish" class="primary">确认发布到顾客网站</button><button id="cancelPreview">继续编辑</button></section><div id="products" class="products"></div></section></main><script nonce="NONCE_VALUE">
'use strict';const $=id=>document.getElementById(id);const labels={name:'产品名称',wood:'木材',size:'尺寸',desc:'产品说明',options:'可讨论的定制项目',price:'价格 / 报价说明'};let initial=[],draft=[],sha='',csrf='',busy=false;
function el(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e}
function status(text){$('status').textContent=text}
function changes(){return draft.flatMap(p=>{const old=initial.find(x=>x.id===p.id);const fields={};for(const k of Object.keys(labels))if((p[k]||'')!==(old[k]||''))fields[k]=p[k]||'';return Object.keys(fields).length?[{id:p.id,fields}]:[]})}
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},cache:'no-store'});const data=await r.json();if(r.status===401){$('loginBox').hidden=false;throw Error(data.error||'请登录')}if(!r.ok)throw Error(data.error||'操作失败');return data}
function render(){const q=$('search').value.trim().toLowerCase();const list=draft.filter(p=>(p.id+' '+p.name).toLowerCase().includes(q));$('products').replaceChildren();$('count').textContent=list.length+' 个产品';for(const p of list){const card=el('article');card.className='product';const photo=el('div');const img=el('img');if(/^products\/[a-zA-Z0-9/_-]+\.(webp|jpg|jpeg|png)$/.test(p.image))img.src='https://qingnian-laowu.netlify.app/'+p.image;img.alt=p.name;photo.append(img,el('small',p.id+' · '+(p.real?'展厅实拍':'AI 示意')));const fields=el('div');fields.className='fields';for(const [k,label]of Object.entries(labels)){const wrap=el('label');if(['desc','options','price'].includes(k))wrap.className='wide';wrap.append(el('span',label));const input=el(k==='desc'?'textarea':'input');input.maxLength={name:80,wood:100,size:160,desc:1600,options:400,price:200}[k];input.value=p[k]||'';input.oninput=()=>{p[k]=input.value;$('previewPanel').hidden=true;status('有 '+changes().length+' 个产品修改尚未发布。')};wrap.append(input);fields.append(wrap)}card.append(photo,fields);$('products').append(card)}}
async function load(preserve=false){try{status('正在读取产品资料…');const data=await api('/admin/api/catalog');csrf=data.csrf;if(preserve&&draft.length&&data.sha!==sha){status('登录成功，但线上资料已经变化。请先复制未发布修改，再重新加载。');$('loginBox').hidden=true;return}if(!preserve||!draft.length){initial=data.products;draft=structuredClone(initial);sha=data.sha;render()}$('editor').hidden=false;$('loginBox').hidden=true;status(preserve?'登录恢复，可以继续编辑。':'资料已加载，修改后请先预览再发布。')}catch(e){status(e.message)}}
$('search').oninput=render;$('resume').onclick=()=>load(true);$('reload').onclick=()=>{if(changes().length&&!confirm('重新加载会丢弃未发布的修改。确定继续？'))return;load()};$('preview').onclick=()=>{const edits=changes();if(!edits.length){status('还没有修改。');return}if(draft.some(p=>!p.name.trim())){status('产品名称不能为空。');return}$('changes').replaceChildren();for(const change of edits){const item=el('div');item.className='change';item.append(el('strong',change.id));const old=initial.find(p=>p.id===change.id);for(const [k,v]of Object.entries(change.fields)){item.append(el('p',labels[k]+'\n原：'+(old[k]||'未填写')+'\n新：'+(v||'未填写')))}$('changes').append(item)}$('previewPanel').hidden=false;$('previewPanel').scrollIntoView({behavior:'smooth'})};$('cancelPreview').onclick=()=>$('previewPanel').hidden=true;
$('publish').onclick=async()=>{if(busy)return;busy=true;document.querySelectorAll('button,input,textarea').forEach(e=>e.disabled=true);try{const data=await api('/admin/api/catalog',{method:'POST',body:JSON.stringify({sha,changes:changes()})});initial=data.products;draft=structuredClone(initial);sha=data.sha;render();$('previewPanel').hidden=true;status(data.message)}catch(e){status(e.message)}finally{busy=false;document.querySelectorAll('button,input,textarea').forEach(e=>e.disabled=false)}};
$('backup').onclick=async()=>{const text=JSON.stringify(changes(),null,2);try{await navigator.clipboard.writeText(text);status('已复制未发布修改，可粘贴到自己的记事本保存。')}catch{const box=el('textarea');box.value=text;$('status').replaceChildren(el('p','请选中下方文字复制保存：'),box);box.select()}};
$('logout').onclick=async()=>{if(changes().length&&!confirm('退出会丢弃未发布修改，确定退出？'))return;try{await api('/admin/api/logout',{method:'POST',body:'{}'});location.reload()}catch(e){status(e.message)}};window.addEventListener('beforeunload',e=>{if(changes().length){e.preventDefault();e.returnValue=''}});load();
</script></body></html>`;

export default async function handler(request) {
 return worker.fetch(request, {GITHUB_CLIENT_ID:process.env.GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET:process.env.GITHUB_CLIENT_SECRET});
}
export const config = {path: ['/admin', '/admin/*']};
